-- HelpTrickBD - Rank Math SEO Postmeta Batch Injector
-- Generated by tools/wp_remediator/
START TRANSACTION;

-- Post ID 1
DELETE FROM wp_postmeta WHERE post_id = 1 AND meta_key IN ('rank_math_focus_keyword', 'rank_math_description', 'rank_math_title');
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (1, 'rank_math_focus_keyword', 'অনার্স ২য় বর্ষ পরীক্ষার গাইড');
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (1, 'rank_math_description', 'জাতীয় বিশ্ববিদ্যালয়ের অনার্স ২য় বর্ষের চূড়ান্ত পরীক্ষা সারা দেশে অত্যন্ত গুরুত্বের সাথে অনুষ্ঠিত হচ্ছে।');
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (1, 'rank_math_title', '%title% %sep% %sitename%');

-- Post ID 282
DELETE FROM wp_postmeta WHERE post_id = 282 AND meta_key IN ('rank_math_focus_keyword', 'rank_math_description', 'rank_math_title');
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (282, 'rank_math_focus_keyword', 'জাতীয় বিশ্ববিদ্যালয় পরীক্ষা ডিজিটালাইজেশন');
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (282, 'rank_math_description', 'বাংলাদেশের উচ্চশিক্ষা ব্যবস্থার ইতিহাসে একটি যুগান্তকারী মাইলফলক স্থাপিত হয়েছে। জাতীয় বিশ্ববিদ্যালয়ের বিশাল পরীক্ষা পরিচালনা, খাতা মূল্যায়ন ও ফলাফল...');
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (282, 'rank_math_title', '%title% %sep% %sitename%');

-- Post ID 283
DELETE FROM wp_postmeta WHERE post_id = 283 AND meta_key IN ('rank_math_focus_keyword', 'rank_math_description', 'rank_math_title');
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (283, 'rank_math_focus_keyword', 'বার্ষিক পরীক্ষার মানবণ্টন ও প্রস্তুতি');
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (283, 'rank_math_description', 'সারসংক্ষেপ উত্তর: জাতীয় শিক্ষাক্রম ও পাঠ্যপুস্তক বোর্ড (NCTB) এবং মাধ্যমিক ও উচ্চশিক্ষা অধিদপ্তর (মাউশি)-এর সর্বশেষ প্রজ্ঞাপন অনুযায়ী ২০২৬ শিক্ষাবর্ষে ৬ষ্ঠ, ৭ম, ৮ম ও ৯ম শ্রেণির বার্ষিক পরীক্ষা মোট ১০০ নম্বরের ভিত্তিতে অনুষ্ঠিত হচ্ছে।');
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (283, 'rank_math_title', '%title% %sep% %sitename%');

-- Post ID 284
DELETE FROM wp_postmeta WHERE post_id = 284 AND meta_key IN ('rank_math_focus_keyword', 'rank_math_description', 'rank_math_title');
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (284, 'rank_math_focus_keyword', 'ডিগ্রি ২য় বর্ষ ইনকোর্স নম্বর এন্ট্রি');
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (284, 'rank_math_description', 'জাতীয় বিশ্ববিদ্যালয় (National University)-এর ২০২৫ সালের ডিগ্রী (পাস) ও সার্টিফিকেট কোর্সের ২য় বর্ষের ইনকোর্স পরীক্ষার নম্বর অনলাইনে এন্ট্রির সময়সীমা আনুষ্ঠানিকভাবে বৃদ্ধি করা হয়েছে।');
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (284, 'rank_math_title', '%title% %sep% %sitename%');

-- Post ID 285
DELETE FROM wp_postmeta WHERE post_id = 285 AND meta_key IN ('rank_math_focus_keyword', 'rank_math_description', 'rank_math_title');
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (285, 'rank_math_focus_keyword', 'অনার্স ২য় বর্ষ পরীক্ষার রুটিন');
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (285, 'rank_math_description', 'জাতীয় বিশ্ববিদ্যালয় (National University)-এর ২০২৫ সালের অনার্স ২য় বর্ষের চূড়ান্ত পরীক্ষার সময়সূচি ও সংশোধিত রুটিন আনুষ্ঠানিকভাবে কার্যকর হয়েছে।');
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES (285, 'rank_math_title', '%title% %sep% %sitename%');

